[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
raid_settlement = "2644KGiENvPpHYbktoMUz2y6TWeQsxz8MpcRhmrakW72"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace --lib"
